@startuml
skinparam {
    monochrome true
    defaultFontName Sarabun
}

title Component Diagram

[User] <.. [StaffController]
[Course] <.. [StaffController]
[Enrollment] <.. [StaffController]
[Timeslot] <.. [StaffController]
[UserRequest] <.. [StaffController]

[Enrollment] --(0-- [Receipt]: ReceiptCreationService

[TeacherController] ..> [User]
[TeacherController] ..> [Course]
[TeacherController] ..> [Timeslot]

[StudentController] ...> [User]
[StudentController] ...> [Course]
[StudentController] ...> [Enrollment]
[StudentController] ...> [UserRequest]
[StudentController] ...> [Timeslot]

[Receipt] -0)- [StudentController]: PDFEasy (Nuxt Module)

[User] <... [UserController]
[UserController] <.. [RegisterController]
[Course] <.. [CourseController]
[Enrollment] <.. [EnrollmentController]
[Receipt] <.. [PaymentController]
@enduml
