@startuml
skinparam monochrome true
skinparam defaultFontName Sarabun
autonumber

title Use Case 2: สร้างคอร์ส
mainframe **sd** CreateCourse

participant "staff:User" as Staff
participant ":CourseController" as CourseController
participant ":Database" as Database

Staff -> CourseController: กดสร้างคอร์ส

activate Staff

activate CourseController
CourseController -> Database: ขอข้อมูลคอร์สและตารางเวลา

activate Database
Database --> CourseController: ข้อมูลคอร์สและตารางเวลา
deactivate Database

CourseController --> Staff: แสดงหน้าสร้างคอร์ส

' loop 1
loop ข้อมูลที่กรอกไม่ถูกต้อง

Staff -> CourseController: กรอกข้อมูลของคอร์ส
Staff -> CourseController: กดปุ่ม "Create"

CourseController -> CourseController: ตรวจสอบข้อมูลที่กรอก

' break 1.1
alt ข้อมูลที่กรอกถูกต้อง

CourseController ->> Database: เขียนข้อมูลของคอร์ส

activate Database
deactivate Database

else ข้อมูลที่กรอกไม่ถูกต้อง

CourseController --> Staff: แจ้งเตือนผู้ใช้ให้ตรวจสอบข้อมูลที่กรอก
deactivate CourseController

' loop 1
end

deactivate Staff
@enduml
