@startuml
!pragma teoz true
skinparam monochrome true
skinparam defaultFontName Sarabun

title Use Case 3: สมัครคอร์ส
mainframe **sd** EnrollCourse

participant "customer:User" as Customer
participant ":EnrollmentController" as EnrollmentController
participant ":Database" as Database

autonumber

activate Customer
Customer -> EnrollmentController: กดปุ่ม "ENROLL COURSE"

activate EnrollmentController
EnrollmentController -> Database: ขอข้อมูลคอร์สและตารางเวลา

activate Database
Database --> EnrollmentController: ข้อมูลคอร์สและตารางเวลา
deactivate Database

EnrollmentController --> Customer: แสดงหน้าสมัครคอร์ส

Customer -> EnrollmentController: เลือกคอร์ส
Customer -> EnrollmentController: กดปุ่ม "View"
EnrollmentController --> Customer: แสดงหน้ายืนยันรายละเอียดคอร์ส

Customer -> EnrollmentController: กดปุ่ม "Confirm"

deactivate EnrollmentController

deactivate Customer
@enduml
