@startuml
skinparam monochrome true
skinparam defaultFontName Sarabun
autonumber

title Use Case 1: สร้างบัญชีผู้ใช้
mainframe **sd** RegisterUser

participant "user:User" as User
participant ":RegisterController" as RegisterController
participant ":UserController" as UserController
participant ":Database" as Database

User -> RegisterController: กดลงทะเบียนบัญชีผู้ใช้

activate User

activate RegisterController
RegisterController --> User: แสดงหน้าฟอร์มลงทะเบียนบัญชีผู้ใช้ระบบ

' loop 1
loop ข้อมูลที่กรอกไม่ถูกต้อง

User -> RegisterController: กรอกข้อมูล
User -> RegisterController: กดปุ่ม "Create Account"
RegisterController -> UserController: ส่งข้อมูลส่วนตัวที่ผู้ใช้กรอก

activate UserController
UserController -> Database: ขอข้อมูลผู้ใช้

activate Database
Database --> UserController: ข้อมูลผู้ใช้
deactivate Database

UserController -> UserController: ตรวจสอบข้อมูลที่ผู้ใช้กรอก

activate UserController
deactivate UserController

' alt 1
alt ข้อมูลที่กรอกถูกต้อง

UserController ->> Database: เขียนข้อมูลผู้ใช้

activate Database
deactivate Database
deactivate UserController

else ข้อมูลที่กรอกไม่ถูกต้อง

RegisterController --> User: แจ้งเตือนผู้ใช้ให้ตรวจสอบข้อมูลที่กรอก

' alt 1
end

deactivate RegisterController

deactivate User
@enduml
