sequenceDiagram
autonumber
    participant staff
    participant system
    system->>staff: แสดงฟอร์มให้เลือกวัน เวลา และรายละเอียดของคอร์สที่จะสร้าง
    activate system
    activate staff
    staff->>staff: กรอกข้อมูลของคอร์ส
    staff->>system: กดปุ่ม “Create”
    deactivate staff
    system->>system: เขียนข้อมูลเกี่ยวกับคอร์สลงในฐานข้อมูล
    deactivate system
