sequenceDiagram
autonumber
    participant user
    participant system
    system->>user: แสดงหน้าฟอร์มลงทะเบียนบัญชีผู้ใช้ระบบ
    activate system
    activate user
    user->>user: กรอกข้อมูล
    user->>system: กดปุ่ม "Create Account"
    system->>system: ตรวจสอบข้อมูลที่ผู้ใช้กรอก
    system->>user: แสดงฟอร์มลงชื่อเข้าใช้ระบบ
    deactivate system
    user->>user: กรอกข้อมูล
    user->>system: กดปุ่ม "Sign In"
    activate system
    system->>system: ตรวจสอบข้อมูลที่ผู้ใช้กรอก
    system->>user: ให้สิทธิ์การเข้าสู่ระบบ
    deactivate system
    deactivate user
