sequenceDiagram
    participant customer
    participant system
    system->>customer: แสดงฟอร์มให้เลือกคอร์สที่จะสมัครจากวันและเวลา
    customer->>customer: เลือกวันและเวลาจากฟอร์ม
    customer->>customer: ยืนยันข้อมูลคอร์สที่กำลังจะสมัคร
    customer->>system: กดปุ่ม “Confirm”
    system->>customer: แสดงหน้าจ่ายค่าคอร์ส
    customer->>customer: อัปโหลดหลักฐานการชำระค่าคอร์ส
    customer->>system: กดปุ่ม “Confirm”
    system->>system: เขียนข้อมูลการสมัครคอร์สลงในฐานข้อมูล
